### ISSUE TITLE
Remaining Milestone Tasks

### ISSUE THREAD

**Issue by golf1052** [team-dd/DoubleDash#7]
# Level Editor
- [x] Level loading
- [x] Export start and end points

(we are skipping triangles in levels for alpha)

# Levels
## World 1
- [ ] Level 1
- [ ] Level 2
- [ ] Level 3
- [ ] Level 4
- [ ] Level 5

- [ ] Critique levels

# Game
- [x] Fix wall jump
- [x] Animated player (existing sprites or something else)
- [x] Parallax background
- [x] Tweak mechanics???

# UI Niceties
- [x] Title screen
- [x] Pause screen
- [ ] Improved dash bar
  - See notes
- [x] Improved speed indication
  - Fade out
- [x] Dash indicator
